
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.time.temporal.ChronoUnit;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JOE
 */
public class Callnotification extends javax.swing.JDialog {

    String usertype, owner;
    String[] cols3={"NO.","CALL NO","DATE OPENED","TIME OPENED","CLIENT","SERVICE DESCRIPTION","TECHNICIAN","CALL AGE"};   
   DefaultTableModel   callstatustableModel=new DefaultTableModel(cols3,0){
   @Override
   public boolean isCellEditable(int row,int column){
        return column == 0;
   }
    };
   SimpleDateFormat sdf=new SimpleDateFormat("dd MMM,yyyy");
   //TimeFormat tf=new TimeFormat();
   Home access=new Home();
    public Callnotification(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
      setLocationRelativeTo(null);
        setTitle("CALL STATUS NOTIFICATION!");
        setResizable(false);
       // getCalls();
       callstatusTable.getTableHeader().setReorderingAllowed(false);
       callstatusTable.getColumnModel().getColumn(0).setPreferredWidth(1);
           
    }
    public void getCalls( String sqlquery, String usertype){
        try {
     Connection connectDb=(Connection)DriverManager.getConnection( access.server,  access.username, access.dbpword);
            PreparedStatement pst=(PreparedStatement)connectDb.prepareStatement(sqlquery); 
            ResultSet rst=pst.executeQuery(); int i=0;
            java.sql.Time timenow=java.sql.Time.valueOf(LocalTime.now());long daysdiff; long hoursdiff;
            java.sql.Date today=java.sql.Date.valueOf(LocalDate.now());
       
  if(usertype.equalsIgnoreCase("USER")){
  messageLabel.setText("You have the following calls with no service entry. Kindly update the calls!");
  }
            
            while(rst.next())  {
        if(rst.getTime(3)!=null){
        daysdiff=ChronoUnit.DAYS.between(LocalDate.parse(rst.getDate(2).toString()), LocalDate.parse(today.toString())) ;
  hoursdiff=ChronoUnit.HOURS.between(LocalTime.parse(rst.getTime(3) .toString()), LocalTime.parse(timenow.toString())) ;
     
  if(hoursdiff<0){
    hoursdiff=ChronoUnit.HOURS.between(LocalTime.parse(rst.getTime(3).toString()), LocalTime.parse(timenow.toString())) ;   
      }
   if(daysdiff>=1||hoursdiff>=2){
  callstatustableModel.addRow(new Object[]{i+1,rst.getString(1),sdf.format(rst.getDate(2)),rst.getTime(3),rst.getString(4),rst.getString(5),rst.getString(6),
          daysdiff+" days, "+(hoursdiff)*-1+" hours"}); 
        }      
        }
        else{
 
        }  
             i++; 
            }
                } catch (SQLException ex) {
            Logger.getLogger(Callnotification.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        messageLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        callstatusTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Call Update Status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 0, 153))); // NOI18N

        messageLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        messageLabel.setForeground(new java.awt.Color(255, 0, 0));
        messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageLabel.setText("The following calls have no service entries. Contact respective technicians to find out service status!");

        callstatusTable.setForeground(new java.awt.Color(153, 0, 153));
        callstatusTable.setModel(callstatustableModel);
        callstatusTable.setFillsViewportHeight(true);
        callstatusTable.setGridColor(new java.awt.Color(153, 0, 153));
        callstatusTable.setRowHeight(30);
        callstatusTable.setRowMargin(2);
        callstatusTable.setSelectionBackground(new java.awt.Color(153, 0, 153));
        jScrollPane1.setViewportView(callstatusTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(messageLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Callnotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Callnotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Callnotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Callnotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Callnotification dialog = new Callnotification(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
               // dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable callstatusTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel messageLabel;
    // End of variables declaration//GEN-END:variables
}
