
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JOE
 */
public class Mileagesettings extends javax.swing.JFrame {

    /**
     * Creates new form Mileagesettings
     */
    DefaultComboBoxModel staffnamecomboModel=new DefaultComboBoxModel();
        Home access=new Home();    String stafflevel;
          DecimalFormat df1=new DecimalFormat("#,###.00"); 
          
    String[] cols={"No.","TOWN NAME"};
   DefaultTableModel   townstableModel=new DefaultTableModel(cols,0){
   @Override
   public boolean isCellEditable(int row,int column){
        return column == 0;
   }  };
   
    public Mileagesettings() {
        initComponents();
         townsTable.getTableHeader().setReorderingAllowed(false);
         townsTable.getColumnModel().getColumn(0).setPreferredWidth(1);
    }
public void getStaffs(){
        try {
            String getcontractsql="SELECT STAFFLEVEL FROM STAFF GROUP BY STAFFLEVEL ORDER BY STAFFLEVEL ASC";
            Connection connectDb=(Connection)DriverManager.getConnection( access.server,  access.username, access.dbpword);
            PreparedStatement pst=(PreparedStatement)connectDb.prepareStatement(getcontractsql);
            ResultSet rst=pst.executeQuery(); int i=0;
            staffnamecomboModel.removeAllElements();
            while(rst.next()){
      staffnamecomboModel.addElement(rst.getString(1)); 
                i++;  
            }
        }
        catch (SQLException ex) {
            Logger.getLogger(Calls.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mileagesettingsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        townTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        townsTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        firstkmTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        firstkmrateTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        extrakmrateTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        accomreceiptedTxt = new javax.swing.JTextField();
        accomreceiptedTxt2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        accomnoreceiptedTxt = new javax.swing.JTextField();
        accomnoreceiptedTxt2 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        breakfastreceiptedTxt = new javax.swing.JTextField();
        breakfastreceiptedTxt2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        breakfastnoreceiptedTxt = new javax.swing.JTextField();
        breakfastnoreceiptedTxt2 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        lunchreceiptedTxt = new javax.swing.JTextField();
        lunchreceiptedTxt2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        lunchnoreceiptedTxt = new javax.swing.JTextField();
        lunchnoreceiptedTxt2 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        dinnerreceiptedTxt = new javax.swing.JTextField();
        dinnerreceiptedTxt2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        dinnernoreceiptedTxt = new javax.swing.JTextField();
        dinnernoreceiptedTxt2 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        laundryTxt = new javax.swing.JTextField();
        laundryTxt2 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        pettiesTxt = new javax.swing.JTextField();
        pettiesTxt2 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        othersTxt = new javax.swing.JTextField();
        othersTxt2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mileagesettingsPanel.setBackground(new java.awt.Color(153, 0, 153));
        mileagesettingsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MILEAGE SETTINGS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Staff Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 0, 102))); // NOI18N

        jLabel2.setText("TOWN:");

        townTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                townTxtKeyReleased(evt);
            }
        });

        jLabel3.setText("STAFF LEVEL:");

        jComboBox1.setModel(staffnamecomboModel);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LIST OF TOWNS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(204, 0, 204))); // NOI18N

        townsTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        townsTable.setModel(townstableModel);
        townsTable.setFillsViewportHeight(true);
        townsTable.setGridColor(new java.awt.Color(204, 0, 204));
        townsTable.setRowHeight(25);
        townsTable.setRowMargin(2);
        townsTable.setSelectionBackground(new java.awt.Color(204, 0, 204));
        jScrollPane2.setViewportView(townsTable);

        jButton2.setText("ADD TOWN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jButton2)
                                        .addGap(0, 141, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBox1, 0, 174, Short.MAX_VALUE)
                                            .addComponent(townTxt))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(townTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Staff Claim Limits ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 0, 153))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Km Claim", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 0, 153))); // NOI18N

        jLabel6.setText("FIRST:");

        firstkmTxt.setText("0");
        firstkmTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstkmTxtActionPerformed(evt);
            }
        });
        firstkmTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstkmTxtKeyTyped(evt);
            }
        });

        jLabel7.setText("KM");

        jLabel8.setText("RATE KES:");

        firstkmrateTxt.setText("0");
        firstkmrateTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstkmrateTxtKeyTyped(evt);
            }
        });

        jLabel9.setText("PER KM");

        jLabel10.setText("EXTRA  KES");

        extrakmrateTxt.setText("0");
        extrakmrateTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                extrakmrateTxtKeyTyped(evt);
            }
        });

        jLabel11.setText("PER KM");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstkmrateTxt)
                            .addComponent(firstkmTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(extrakmrateTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(firstkmTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(firstkmrateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(extrakmrateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Accomodation Claim", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 0, 153))); // NOI18N

        jLabel12.setText("RECEIPTED:");

        accomreceiptedTxt.setText("0");
        accomreceiptedTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                accomreceiptedTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                accomreceiptedTxtKeyTyped(evt);
            }
        });

        accomreceiptedTxt2.setEditable(false);
        accomreceiptedTxt2.setText("0.00");
        accomreceiptedTxt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                accomreceiptedTxt2KeyTyped(evt);
            }
        });

        jLabel13.setText("NO RECEIPT:");

        accomnoreceiptedTxt.setText("0");
        accomnoreceiptedTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                accomnoreceiptedTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                accomnoreceiptedTxtKeyTyped(evt);
            }
        });

        accomnoreceiptedTxt2.setEditable(false);
        accomnoreceiptedTxt2.setText("0.00");
        accomnoreceiptedTxt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                accomnoreceiptedTxt2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(13, 13, 13)
                        .addComponent(accomnoreceiptedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(accomnoreceiptedTxt2, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(accomreceiptedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(accomreceiptedTxt2)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(accomreceiptedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accomreceiptedTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(accomnoreceiptedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(accomnoreceiptedTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Breakfast Claim", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 0, 153))); // NOI18N

        jLabel14.setText("RECEIPTED:");

        breakfastreceiptedTxt.setText("0");
        breakfastreceiptedTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                breakfastreceiptedTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                breakfastreceiptedTxtKeyTyped(evt);
            }
        });

        breakfastreceiptedTxt2.setEditable(false);
        breakfastreceiptedTxt2.setText("0.00");
        breakfastreceiptedTxt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                breakfastreceiptedTxt2KeyTyped(evt);
            }
        });

        jLabel15.setText("NO RECEIPT:");

        breakfastnoreceiptedTxt.setText("0");
        breakfastnoreceiptedTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                breakfastnoreceiptedTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                breakfastnoreceiptedTxtKeyTyped(evt);
            }
        });

        breakfastnoreceiptedTxt2.setEditable(false);
        breakfastnoreceiptedTxt2.setText("0.00");
        breakfastnoreceiptedTxt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                breakfastnoreceiptedTxt2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(13, 13, 13)
                        .addComponent(breakfastnoreceiptedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(breakfastnoreceiptedTxt2, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(breakfastreceiptedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(breakfastreceiptedTxt2)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(breakfastreceiptedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(breakfastreceiptedTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(breakfastnoreceiptedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(breakfastnoreceiptedTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lunch Claim", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 0, 153))); // NOI18N

        jLabel16.setText("RECEIPTED:");

        lunchreceiptedTxt.setText("0");
        lunchreceiptedTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lunchreceiptedTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lunchreceiptedTxtKeyTyped(evt);
            }
        });

        lunchreceiptedTxt2.setEditable(false);
        lunchreceiptedTxt2.setText("0.00");

        jLabel17.setText("NO RECEIPT:");

        lunchnoreceiptedTxt.setText("0");
        lunchnoreceiptedTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lunchnoreceiptedTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lunchnoreceiptedTxtKeyTyped(evt);
            }
        });

        lunchnoreceiptedTxt2.setEditable(false);
        lunchnoreceiptedTxt2.setText("0.00");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(13, 13, 13)
                        .addComponent(lunchnoreceiptedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lunchnoreceiptedTxt2, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(lunchreceiptedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lunchreceiptedTxt2)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lunchreceiptedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lunchreceiptedTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lunchnoreceiptedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lunchnoreceiptedTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dinner Claim", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 0, 153))); // NOI18N

        jLabel18.setText("RECEIPTED:");

        dinnerreceiptedTxt.setText("0");
        dinnerreceiptedTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dinnerreceiptedTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dinnerreceiptedTxtKeyTyped(evt);
            }
        });

        dinnerreceiptedTxt2.setEditable(false);
        dinnerreceiptedTxt2.setText("0.00");

        jLabel19.setText("NO RECEIPT:");

        dinnernoreceiptedTxt.setText("0");
        dinnernoreceiptedTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dinnernoreceiptedTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dinnernoreceiptedTxtKeyTyped(evt);
            }
        });

        dinnernoreceiptedTxt2.setEditable(false);
        dinnernoreceiptedTxt2.setText("0.00");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(13, 13, 13)
                        .addComponent(dinnernoreceiptedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dinnernoreceiptedTxt2, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(dinnerreceiptedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dinnerreceiptedTxt2)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(dinnerreceiptedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dinnerreceiptedTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dinnernoreceiptedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dinnernoreceiptedTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Laundry Per Week Claim", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 0, 153))); // NOI18N

        jLabel20.setText("KES:");

        laundryTxt.setText("0");
        laundryTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                laundryTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                laundryTxtKeyTyped(evt);
            }
        });

        laundryTxt2.setEditable(false);
        laundryTxt2.setText("0.00");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel20)
                    .addGap(18, 18, 18)
                    .addComponent(laundryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(laundryTxt2, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(58, 58, 58)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(laundryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(laundryTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(66, Short.MAX_VALUE)))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Petties", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 0, 153))); // NOI18N

        jLabel21.setText("KES:");

        pettiesTxt.setText("0");
        pettiesTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pettiesTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pettiesTxtKeyTyped(evt);
            }
        });

        pettiesTxt2.setEditable(false);
        pettiesTxt2.setText("0.00");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(pettiesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pettiesTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(pettiesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pettiesTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Other Claims", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 0, 153))); // NOI18N

        jLabel22.setText("KES:");

        othersTxt.setText("0");
        othersTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                othersTxtActionPerformed(evt);
            }
        });
        othersTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                othersTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                othersTxtKeyTyped(evt);
            }
        });

        othersTxt2.setEditable(false);
        othersTxt2.setText("0.00");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(othersTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(othersTxt2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(othersTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(othersTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(178, 178, 178))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout mileagesettingsPanelLayout = new javax.swing.GroupLayout(mileagesettingsPanel);
        mileagesettingsPanel.setLayout(mileagesettingsPanelLayout);
        mileagesettingsPanelLayout.setHorizontalGroup(
            mileagesettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        mileagesettingsPanelLayout.setVerticalGroup(
            mileagesettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mileagesettingsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mileagesettingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
   stafflevel=""+jComboBox1.getSelectedItem();
   
    }//GEN-LAST:event_jComboBox1ActionPerformed
public void      getstaffClaims(){
try {
    String getcontractsql="SELECT * FROM MILEAGESETTINGS WHERE STAFFLEVEL="+stafflevel+" AND TOWN LIKE '"+townTxt.getText()+"%'";
            Connection connectDb=(Connection)DriverManager.getConnection( access.server,  access.username, access.dbpword);
            PreparedStatement pst=(PreparedStatement)connectDb.prepareStatement(getcontractsql);
            ResultSet rst=pst.executeQuery(); int i=0;
           while(rst.next()){
  firstkmTxt.setText(String.valueOf(rst.getInt(3)));
firstkmrateTxt.setText(String.valueOf(rst.getInt(4)));
 extrakmrateTxt.setText(String.valueOf(rst.getInt(5)));
 
 accomreceiptedTxt.setText(String.valueOf(rst.getInt(6)));
  accomreceiptedTxt2.setText("KES "+df1.format( (rst.getInt(6))));
  
 accomnoreceiptedTxt.setText(String.valueOf(rst.getInt(7)));
  accomnoreceiptedTxt2.setText("KES "+df1.format( (rst.getInt(7))));
  
  breakfastreceiptedTxt.setText(String.valueOf(rst.getInt(8)));
  breakfastreceiptedTxt2.setText("KES "+df1.format( (rst.getInt(8))));

breakfastnoreceiptedTxt.setText(String.valueOf(rst.getInt(9)));
 breakfastnoreceiptedTxt2.setText("KES "+df1.format( (rst.getInt(9))));
 
     lunchreceiptedTxt.setText(String.valueOf(rst.getInt(10)));
     lunchreceiptedTxt2.setText("KES "+df1.format( (rst.getInt(10))));
     
 lunchnoreceiptedTxt.setText(String.valueOf(rst.getInt(11)));
  lunchnoreceiptedTxt2.setText("KES "+df1.format( (rst.getInt(11))));
  
  dinnerreceiptedTxt.setText(String.valueOf(rst.getInt(12)));
  dinnerreceiptedTxt2.setText("KES "+df1.format( (rst.getInt(12))));
  
dinnernoreceiptedTxt.setText(String.valueOf(rst.getInt(13)));
dinnernoreceiptedTxt2.setText("KES "+df1.format( (rst.getInt(13))));

    laundryTxt.setText(String.valueOf(rst.getInt(14)));
    laundryTxt2.setText("KES "+df1.format( (rst.getInt(14)))); 
    
 pettiesTxt.setText(String.valueOf(rst.getInt(15)));
  pettiesTxt2.setText("KES "+df1.format( (rst.getInt(15)))); 
  
    othersTxt.setText(String.valueOf(rst.getInt(16)));
     othersTxt2.setText("KES "+df1.format( (rst.getInt(16)))); 
    
      i++;  
          }
           if(i<1){
            clearFields();
            }
        }
        catch (SQLException ex) {
            Logger.getLogger(Calls.class.getName()).log(Level.SEVERE, null, ex);
        }

}
    private void firstkmTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstkmTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstkmTxtActionPerformed
public void clearFields(){
 firstkmTxt.setText("0");
firstkmrateTxt.setText("0");
 extrakmrateTxt.setText("0");
 
 accomreceiptedTxt.setText("0");
  accomreceiptedTxt2.setText(null);
  
 accomnoreceiptedTxt.setText("0");
  accomnoreceiptedTxt2.setText(null);
  
  breakfastreceiptedTxt.setText("0");
  breakfastreceiptedTxt2.setText(null);

breakfastnoreceiptedTxt.setText("0");
 breakfastnoreceiptedTxt2.setText(null);
 
     lunchreceiptedTxt.setText("0");
     lunchreceiptedTxt2.setText(null);
     
 lunchnoreceiptedTxt.setText("0");
  lunchnoreceiptedTxt2.setText(null);
  
  dinnerreceiptedTxt.setText("0");
  dinnerreceiptedTxt2.setText(null);
  
dinnernoreceiptedTxt.setText("0");
dinnernoreceiptedTxt2.setText(null);

    laundryTxt.setText("0");
    laundryTxt2.setText(null);
    
 pettiesTxt.setText("0");
  pettiesTxt2.setText(null);
  
    othersTxt.setText("0");
     othersTxt2.setText(null);
    

}
    private void firstkmTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstkmTxtKeyTyped
     char c=evt.getKeyChar();
        if((c>='0')&&(c<='9')){
        } else {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_firstkmTxtKeyTyped

    private void firstkmrateTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstkmrateTxtKeyTyped
         char c=evt.getKeyChar();
        if((c>='0')&&(c<='9')){
        } else {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_firstkmrateTxtKeyTyped

    private void extrakmrateTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_extrakmrateTxtKeyTyped
           char c=evt.getKeyChar();
        if((c>='0')&&(c<='9')){
        } else {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_extrakmrateTxtKeyTyped

    private void accomreceiptedTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accomreceiptedTxtKeyTyped
           char c=evt.getKeyChar();
        if((c>='0')&&(c<='9')){
        } else {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_accomreceiptedTxtKeyTyped

    private void accomreceiptedTxt2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accomreceiptedTxt2KeyTyped
          char c=evt.getKeyChar();
        if((c>='0')&&(c<='9')){
        } else {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_accomreceiptedTxt2KeyTyped

    private void accomnoreceiptedTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accomnoreceiptedTxtKeyTyped
          char c=evt.getKeyChar();
        if((c>='0')&&(c<='9')){
        } else {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_accomnoreceiptedTxtKeyTyped

    private void accomnoreceiptedTxt2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accomnoreceiptedTxt2KeyTyped
           char c=evt.getKeyChar();
        if((c>='0')&&(c<='9')){
        } else {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_accomnoreceiptedTxt2KeyTyped

    private void breakfastreceiptedTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_breakfastreceiptedTxtKeyTyped
          char c=evt.getKeyChar();
        if((c>='0')&&(c<='9')){
        } else {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_breakfastreceiptedTxtKeyTyped

    private void breakfastreceiptedTxt2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_breakfastreceiptedTxt2KeyTyped
            char c=evt.getKeyChar();
        if((c>='0')&&(c<='9')){
        } else {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_breakfastreceiptedTxt2KeyTyped

    private void breakfastnoreceiptedTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_breakfastnoreceiptedTxtKeyTyped
        char c=evt.getKeyChar();
        if((c>='0')&&(c<='9')){
        } else {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_breakfastnoreceiptedTxtKeyTyped

    private void breakfastnoreceiptedTxt2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_breakfastnoreceiptedTxt2KeyTyped
           char c=evt.getKeyChar();
        if((c>='0')&&(c<='9')){
        } else {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_breakfastnoreceiptedTxt2KeyTyped

    private void lunchreceiptedTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lunchreceiptedTxtKeyTyped
           char c=evt.getKeyChar();
        if((c>='0')&&(c<='9')){
        } else {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_lunchreceiptedTxtKeyTyped

    private void lunchnoreceiptedTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lunchnoreceiptedTxtKeyTyped
        char c=evt.getKeyChar();
        if((c>='0')&&(c<='9')){
        } else {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_lunchnoreceiptedTxtKeyTyped

    private void dinnerreceiptedTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dinnerreceiptedTxtKeyTyped
          char c=evt.getKeyChar();
        if((c>='0')&&(c<='9')){
        } else {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_dinnerreceiptedTxtKeyTyped

    private void dinnernoreceiptedTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dinnernoreceiptedTxtKeyTyped
           char c=evt.getKeyChar();
        if((c>='0')&&(c<='9')){
        } else {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_dinnernoreceiptedTxtKeyTyped

    private void laundryTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_laundryTxtKeyTyped
           char c=evt.getKeyChar();
        if((c>='0')&&(c<='9')){
        } else {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_laundryTxtKeyTyped

    private void pettiesTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pettiesTxtKeyTyped
          char c=evt.getKeyChar();
        if((c>='0')&&(c<='9')){
        } else {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_pettiesTxtKeyTyped

    private void othersTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_othersTxtKeyTyped
          char c=evt.getKeyChar();
        if((c>='0')&&(c<='9')){
        } else {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_othersTxtKeyTyped

    private void othersTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_othersTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_othersTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int g=townsTable.getRowCount();
        
        if(stafflevel==null){
  JOptionPane.showMessageDialog(null, "Please select staff level!","Staff Level Required",JOptionPane.WARNING_MESSAGE);   
     }
        if(g<1){
  JOptionPane.showMessageDialog(null, "Please add at least 1 town !","Town Required",JOptionPane.WARNING_MESSAGE);
      }else{
          
          try {
              Connection connectDb=(Connection)DriverManager.getConnection( access.server,  access.username, access.dbpword);
                String checkclaimsql;   PreparedStatement pst2;  ResultSet rst;   int h=0;
                
   int choice=JOptionPane.showConfirmDialog(null, "Save Mileage Claim limits for Staff level "+stafflevel+" for added towns?","Confirm",JOptionPane.YES_NO_OPTION);
              if(choice==JOptionPane.YES_OPTION){              
  for(int r=0;r<g;r++){
   checkclaimsql="SELECT STAFFLEVEL, TOWN FROM MILEAGESETTINGS WHERE STAFFLEVEL='"+stafflevel+"' and TOWN='"+String.valueOf(townsTable.getValueAt(r, 1))+"'";
  pst2=(PreparedStatement)connectDb.prepareStatement(checkclaimsql);
   rst=pst2.executeQuery();  int u=0; 
  while(rst.next()){
                  u++;
              } 
  
    if(u<1){
  
        
    String insertsql="INSERT INTO MILEAGESETTINGS VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";              
     PreparedStatement pst4=(PreparedStatement)connectDb.prepareStatement(insertsql);  
  
    pst4.setString(1, stafflevel);
     pst4.setString(2,String.valueOf(townsTable.getValueAt(r, 1))); 
    pst4.setInt(3, Integer.parseInt(firstkmTxt.getText()));
    pst4.setInt(4, Integer.parseInt(firstkmrateTxt.getText()));
    pst4.setInt(5, Integer.parseInt(extrakmrateTxt.getText()));
    pst4.setInt(6, Integer.parseInt(accomreceiptedTxt.getText()));
    pst4.setInt(7, Integer.parseInt(accomnoreceiptedTxt.getText()));
    pst4.setInt(8, Integer.parseInt(breakfastreceiptedTxt.getText()));
    pst4.setInt(9, Integer.parseInt(breakfastnoreceiptedTxt.getText()));
    pst4.setInt(10, Integer.parseInt(lunchreceiptedTxt.getText()));
    pst4.setInt(11, Integer.parseInt(lunchnoreceiptedTxt.getText()));
    pst4.setInt(12, Integer.parseInt(dinnerreceiptedTxt.getText()));
    pst4.setInt(13, Integer.parseInt(dinnernoreceiptedTxt.getText()));
    pst4.setInt(14, Integer.parseInt(laundryTxt.getText()));
    pst4.setInt(15, Integer.parseInt(pettiesTxt.getText()));
    pst4.setInt(16, Integer.parseInt(othersTxt.getText()));
  h=  pst4.executeUpdate();
     
               }
     else{
   String updateclaimsql="UPDATE MILEAGESETTINGS SET FIRSTKM=?,RATE_FIRSTKM=?,RATE_EXTRAKM=?,ACCOM_RECEIPTED=?,"
              + "ACCOM_NORECEPT=?,BREAKF_RECEIPT=?,BREAKF_NORECEPT=?,LUNCH_RECEIPT=?,LUNCH_NORECEPT=?,"
              + "DINNER_RECEIPT=?,DINNER_NORECEPT=?,LAUNDRY=?,PETTIES=?,OTHERS=? WHERE TOWN='"+String.valueOf(townsTable.getValueAt(r, 1))+"' "
              + "AND STAFFLEVEL="+stafflevel+" ";              
     PreparedStatement pst4=(PreparedStatement)connectDb.prepareStatement(updateclaimsql);  
   pst4.setInt(1, Integer.parseInt(firstkmTxt.getText()));
    pst4.setInt(2, Integer.parseInt(firstkmrateTxt.getText()));pst4.setInt(3, Integer.parseInt(extrakmrateTxt.getText()));
    pst4.setInt(4, Integer.parseInt(accomreceiptedTxt.getText()));pst4.setInt(5, Integer.parseInt(accomnoreceiptedTxt.getText()));
    pst4.setInt(6, Integer.parseInt(breakfastreceiptedTxt.getText()));pst4.setInt(7, Integer.parseInt(breakfastnoreceiptedTxt.getText()));
    pst4.setInt(8, Integer.parseInt(lunchreceiptedTxt.getText()));pst4.setInt(9, Integer.parseInt(lunchnoreceiptedTxt.getText()));
    pst4.setInt(10, Integer.parseInt(dinnerreceiptedTxt.getText()));pst4.setInt(11, Integer.parseInt(dinnernoreceiptedTxt.getText()));
    pst4.setInt(12, Integer.parseInt(laundryTxt.getText()));pst4.setInt(13, Integer.parseInt(pettiesTxt.getText()));
    pst4.setInt(14, Integer.parseInt(othersTxt.getText()));
 h=  pst4.executeUpdate();
             
  }  
  }            
           
              }
  if(h>0){
   JOptionPane.showMessageDialog(null, "Mileage Settings for Staff level "+stafflevel+" for added towns saved successfully","Successful",JOptionPane.INFORMATION_MESSAGE);
  }  
 
          
                   } catch (SQLException ex) {
              Logger.getLogger(Mileagesettings.class.getName()).log(Level.SEVERE, null, ex);
          }
      
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void accomreceiptedTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accomreceiptedTxtKeyReleased
        if(accomreceiptedTxt.getText().trim().length()!=0){
            int value=Integer.parseInt(accomreceiptedTxt.getText());
            if(value>0){
                accomreceiptedTxt2.setText( "KES. "+df1.format(value));
            }
        }
    }//GEN-LAST:event_accomreceiptedTxtKeyReleased

    private void accomnoreceiptedTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accomnoreceiptedTxtKeyReleased
      if( accomnoreceiptedTxt.getText().trim().length()!=0){
            int value=Integer.parseInt( accomnoreceiptedTxt.getText());
            if(value>0){
                accomnoreceiptedTxt2.setText( "KES. "+df1.format(value));
            }
        }
    }//GEN-LAST:event_accomnoreceiptedTxtKeyReleased

    private void breakfastreceiptedTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_breakfastreceiptedTxtKeyReleased
       if( breakfastreceiptedTxt.getText().trim().length()!=0){
            int value=Integer.parseInt( breakfastreceiptedTxt.getText());
            if(value>0){
                breakfastreceiptedTxt2.setText( "KES. "+df1.format(value));
            }
        }
    }//GEN-LAST:event_breakfastreceiptedTxtKeyReleased

    private void breakfastnoreceiptedTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_breakfastnoreceiptedTxtKeyReleased
        if( breakfastnoreceiptedTxt.getText().trim().length()!=0){
            int value=Integer.parseInt( breakfastnoreceiptedTxt.getText());
            if(value>0){
                breakfastnoreceiptedTxt2.setText( "KES. "+df1.format(value));
            }
        }
    }//GEN-LAST:event_breakfastnoreceiptedTxtKeyReleased

    private void lunchreceiptedTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lunchreceiptedTxtKeyReleased
          if(  lunchreceiptedTxt.getText().trim().length()!=0){
            int value=Integer.parseInt(  lunchreceiptedTxt.getText());
            if(value>0){
                 lunchreceiptedTxt2.setText( "KES. "+df1.format(value));
            }
        }
    }//GEN-LAST:event_lunchreceiptedTxtKeyReleased

    private void lunchnoreceiptedTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lunchnoreceiptedTxtKeyReleased
        if(  lunchnoreceiptedTxt.getText().trim().length()!=0){
            int value=Integer.parseInt(  lunchnoreceiptedTxt.getText());
            if(value>0){
                 lunchnoreceiptedTxt2.setText( "KES. "+df1.format(value));
            }
        }
    }//GEN-LAST:event_lunchnoreceiptedTxtKeyReleased

    private void dinnerreceiptedTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dinnerreceiptedTxtKeyReleased
        if(  dinnerreceiptedTxt.getText().trim().length()!=0){
            int value=Integer.parseInt(  dinnerreceiptedTxt.getText());
            if(value>0){
                 dinnerreceiptedTxt2.setText( "KES. "+df1.format(value));
            }
        }
    }//GEN-LAST:event_dinnerreceiptedTxtKeyReleased

    private void dinnernoreceiptedTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dinnernoreceiptedTxtKeyReleased
         if(   dinnernoreceiptedTxt.getText().trim().length()!=0){
            int value=Integer.parseInt(   dinnernoreceiptedTxt.getText());
            if(value>0){
                  dinnernoreceiptedTxt2.setText( "KES. "+df1.format(value));
            }
        }
    }//GEN-LAST:event_dinnernoreceiptedTxtKeyReleased

    private void laundryTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_laundryTxtKeyReleased
      if(   laundryTxt.getText().trim().length()!=0){
            int value=Integer.parseInt(   laundryTxt.getText());
            if(value>0){
                  laundryTxt2.setText( "KES. "+df1.format(value));
            }
        }
    }//GEN-LAST:event_laundryTxtKeyReleased

    private void pettiesTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pettiesTxtKeyReleased
        if(   pettiesTxt.getText().trim().length()!=0){
            int value=Integer.parseInt(   pettiesTxt.getText());
            if(value>0){
                  pettiesTxt2.setText( "KES. "+df1.format(value));
            }
        }
    }//GEN-LAST:event_pettiesTxtKeyReleased

    private void othersTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_othersTxtKeyReleased
       if(   othersTxt.getText().trim().length()!=0){
            int value=Integer.parseInt(   othersTxt.getText());
            if(value>0){
                  othersTxt2.setText( "KES. "+df1.format(value));
            }
        }
    }//GEN-LAST:event_othersTxtKeyReleased

    private void townTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_townTxtKeyReleased
      getstaffClaims();
    }//GEN-LAST:event_townTxtKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    if(townTxt.getText().isEmpty()){
    JOptionPane.showMessageDialog(null, "Please enter town name!","Town Name Required",JOptionPane.WARNING_MESSAGE);
    }else{
    int g=townsTable.getRowCount();
    if(g<1){
    townstableModel.addRow(new Object[]{g+1,townTxt.getText()});  townTxt.setText(null); 
    }else{
    for(int f=0;f<g;f++){
    if(townTxt.getText().equalsIgnoreCase(String.valueOf(townsTable.getValueAt(f, 1)))){
   JOptionPane.showMessageDialog(null,townTxt.getText()+ " already exists!","Duplicate Town Name",JOptionPane.WARNING_MESSAGE);
  townTxt.setText(null);  break; 
   }
    else{
      townstableModel.addRow(new Object[]{g+1,townTxt.getText()});  townTxt.setText(null);break;
    }
    }
    }
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accomnoreceiptedTxt;
    private javax.swing.JTextField accomnoreceiptedTxt2;
    private javax.swing.JTextField accomreceiptedTxt;
    private javax.swing.JTextField accomreceiptedTxt2;
    private javax.swing.JTextField breakfastnoreceiptedTxt;
    private javax.swing.JTextField breakfastnoreceiptedTxt2;
    private javax.swing.JTextField breakfastreceiptedTxt;
    private javax.swing.JTextField breakfastreceiptedTxt2;
    private javax.swing.JTextField dinnernoreceiptedTxt;
    private javax.swing.JTextField dinnernoreceiptedTxt2;
    private javax.swing.JTextField dinnerreceiptedTxt;
    private javax.swing.JTextField dinnerreceiptedTxt2;
    private javax.swing.JTextField extrakmrateTxt;
    private javax.swing.JTextField firstkmTxt;
    private javax.swing.JTextField firstkmrateTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField laundryTxt;
    private javax.swing.JTextField laundryTxt2;
    private javax.swing.JTextField lunchnoreceiptedTxt;
    private javax.swing.JTextField lunchnoreceiptedTxt2;
    private javax.swing.JTextField lunchreceiptedTxt;
    private javax.swing.JTextField lunchreceiptedTxt2;
    public javax.swing.JPanel mileagesettingsPanel;
    private javax.swing.JTextField othersTxt;
    private javax.swing.JTextField othersTxt2;
    private javax.swing.JTextField pettiesTxt;
    private javax.swing.JTextField pettiesTxt2;
    private javax.swing.JTextField townTxt;
    private javax.swing.JTable townsTable;
    // End of variables declaration//GEN-END:variables
}
