
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JOE
 */
public class NewJDialog extends javax.swing.JDialog {

    Home access=new Home();
    public NewJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
         initComponents();
        try {
           Connection connectDb=(Connection)DriverManager.getConnection( access.server,  access.username, access.dbpword);
           String getcallssql="SELECT CALLS.CALL_NO,SERVICE.SERVICE_NO,SERVICE.SERVICE_DATE,SERVICE.FROM2,SERVICE.TO2,CONTRACTS.CONTRACT_NO, SERVICE.EQUIP_MODEL,"
          + "SERVICE.SERIAL,SERVICE.LOCATION,CALLS.TO_DO,SERVICE.ACTION,SERVICE.STATUS,CLIENTS.CLIENTNAME,STAFF.STAFFNAME,CLAIMS.STATUS,SERVICE.TOWN,CLAIMS.CLAIMNO "
          + ",SUPPLY_REQUESTS.CLIENTNO,CLIENTS.CLIENTNAME FROM CALLS "
                    + "LEFT JOIN SERVICE ON CALLS.CALL_NO = SERVICE.CALL_NO "
                    + " LEFT JOIN CONTRACTS ON CALLS.CONTRACT_NO=CONTRACTS.CONTRACT_NO "
            + "LEFT JOIN CLIENTS ON CONTRACTS.CLIENT_NO=CLIENTS.CLIENT_NO "
            + " LEFT JOIN STAFF ON CALLS.TECHNICIAN=STAFF.STAFFNO "
            + "LEFT JOIN CLAIMS ON SERVICE.SERVICE_NO=CLAIMS.SERVICE_NO "
                   + "left join SUPPLY_REQUESTS ON CALLS.CONTRACT_NO=SUPPLY_REQUESTS.CSRNO "
           + "WHERE CALLS.CALL_NO LIKE 'TS2018/003%'"
         + " ORDER BY SERVICE.SERVICE_DATE DESC";
          PreparedStatement  pst2=(PreparedStatement)connectDb.prepareStatement(getcallssql);
          ResultSet rst=pst2.executeQuery();
        while(rst.next()){
        // System.out.println("Update state :"+r);
       System.out.println("CLIENT NAME:"+rst.getString(13));   
        }
        } catch (SQLException ex) {
            Logger.getLogger(NewJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 877, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJDialog dialog = new NewJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
